# Change these first
owner: vasilvestre # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: My socials
    url: https://vasilvestre.github.io/
  - name: Client website
    url: https://www.smsp.fr/
  - name: Second client website
    url: https://www.dumont-securite.fr/
  # Discontinued
  #- name: Multistream, OSS project
  #  url: https://multistream-tools.live/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: I track website uptime for free in this repository.
  navbar:
    - title: Status
      href: /
    - title: My cool website
      href: https://vasilvestre.github.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
